export const episodes = [
	{
		title: 'Episode 1: Movie Title',
		subtitle: 'Subtitle',
		shortDescription: 'Short description of the episode',
		description: 'Description of episode',
		link: 'https://www.example.com/episode1',
		guid: '1',
		thumbnail: '/images/tcm.jpg',
		thumbnailComparison: 'https://www.example.com/episode1-thumbnail-comparison',
		embedPlayer: 'https://www.example.com/embed-player/episode1',
		number: 1,
		season: 1,
		releaseDate: '2022-12-23',
		film: {
			title: 'Movie Title',
			releaseYear: 2022,
			director: 'Director Name',
			writer: 'Writer Name',
			cast: ['Actor 1', 'Actor 2', 'Actor 3'],
			backdrop: 'https://www.example.com/movie-backdrop.jpg',
			poster: 'https://www.example.com/movie-poster.jpg',
			keywords: ['keyword1', 'keyword2', 'keyword3'],
			heroframe: 'https://www.example.com/movie-heroframe.jpg',
		},
	},
	{
		title: 'Episode 2: Movie Title',
		subtitle: 'Subtitle',
		shortDescription: 'Short description of the episode',
		description: 'Description of episode',
		link: 'https://www.example.com/episode2',
		guid: '2',
		thumbnail: 'https://www.example.com/episode2-thumbnail.jpg',
		thumbnailComparison: 'https://www.example.com/episode2-thumbnail-comparison',
		embedPlayer: 'https://www.example.com/embed-player/episode2',
		number: 2,
		season: 1,
		releaseDate: '2022-12-30',
		film: {
			title: 'Movie Title',
			releaseYear: 2022,
			director: 'Director Name',
			writer: 'Writer Name',
			cast: ['Actor 1', 'Actor 2', 'Actor 3'],
			backdrop: 'https://www.example.com/movie-backdrop.jpg',
			poster: 'https://www.example.com/movie-poster.jpg',
			keywords: ['keyword1', 'keyword2', 'keyword3'],
			heroframe: 'https://www.example.com/movie-heroframe.jpg',
		},
	},
	{
		title: 'Episode 3: Movie Title',
		subtitle: 'Subtitle',
		shortDescription: 'Short description of the episode',
		description: 'Description of episode',
		link: 'https://www.example.com/episode3',
		guid: '3',
		thumbnail: 'https://www.example.com/episode3-thumbnail.jpg',
		thumbnailComparison: 'https://www.example.com/episode3-thumbnail-comparison',
		embedPlayer: 'https://www.example.com/embed-player/episode3',
		number: 3,
		season: 1,
		releaseDate: '2023-01-06',
		film: {
			title: 'Movie Title',
			releaseYear: 2023,
			director: 'Director Name',
			writer: 'Writer Name',
			cast: ['Actor 1', 'Actor 2', 'Actor 3'],
			backdrop: 'https://www.example.com/movie-backdrop.jpg',
			poster: 'https://www.example.com/movie-poster.jpg',
			keywords: ['keyword1', 'keyword2', 'keyword3'],
			heroframe: 'https://www.example.com/movie-heroframe.jpg',
		},
	},
];
