import Head from 'next/head';

//components
import Styling from '../components/Styling';

export default function Home() {
	return (
		<>
			<Head>
				<title>Feargenics: A Horror Film Podcast</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Styling></Styling>
		</>
	);
}
